server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

polar:
  greeting: Welcome to the local book catalog!

spring:
  datasource:
    username: oscar
    password: oscar
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000 # maximum time (ms) to spend waiting to get a connection from the pool
      maximum-pool-size: 5 # maximum number of connections HikariCP will keep in the pool